name: CI
env:
  CI: true

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Notify Push
      uses: appleboy/telegram-action@0.0.7
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: CI event triggered for [this commit](https://github.com/${{github.repository}}/commit/${{github.sha}}) by [${{github.actor}}](https://github.com/${{github.actor}}).
    - uses: actions/checkout@v2
    - name: Setup Node
      if: success()
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      if: success()
      run: npm install
    - name: Lint
      if: success()
      run: npm run lint
    - name: Test & Coverage
      if: success()
      run: npm run test -- --collect-coverage
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: coverage/
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/coverage-final.json
        fail_ci_if_error: false
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: msociety/msocietybot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        tag_names: true
        tag_semver: true
    - name: Notify Completed
      uses: appleboy/telegram-action@0.0.7
      if: success() || failure()
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: CI completed with status ${{job.status}} for [this commit](https://github.com/${{github.repository}}/commit/${{github.sha}}) by [${{github.actor}}](https://github.com/${{github.actor}}).

